version: '3.4'

services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=worksheets
    logging:
        options:
            max-size: 10m
            max-file: '3'
    ports:
        - '5432:5432'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
  frontend:
    image: node:16
    volumes: 
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    working_dir: /app/frontend
    command: ["npm", "run", "sd:fe"]
  backend:
    image: node:16
    volumes: 
      - ./backend:/app/backend
    ports:
      - 5001:5001
    working_dir: /app/backend
    command: ["npm", "run", "sd:be"]
    environment:
        - NODE_ENV=development
    