# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180605_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippetFoo',
            new_name='Snippet',
        ),
    ]
