# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_snippet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Source'),
        ),
    ]
