# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_scraper', '0008_auto_20180305_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
    ]
