# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributors', models.TextField()),
                ('coordinates', models.TextField()),
                ('created_at_in_seconds', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('favorited', models.BooleanField()),
                ('twitter_id', models.IntegerField()),
                ('in_reply_to_screen_name', models.TextField()),
                ('in_reply_to_status_id', models.TextField()),
                ('in_reply_to_user_id', models.TextField()),
                ('lang', models.TextField()),
                ('possibly_sensitive', models.BooleanField()),
                ('quoted_status', models.TextField()),
                ('quoted_status_id', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('retweeted', models.BooleanField()),
                ('retweeted_status', models.TextField()),
                ('text', models.TextField()),
                ('hashtag', models.ManyToManyField(related_name='hashtag', to='twitter_scraper.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('screen_name', models.TextField()),
                ('location', models.TextField()),
                ('created_at', models.DateField()),
                ('description', models.TextField()),
                ('favourites_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('twitter_id', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ManyToManyField(related_name='user', to='twitter_scraper.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_mentions',
            field=models.ManyToManyField(related_name='user_mentions', to='twitter_scraper.User'),
        ),
    ]
