# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_scraper', '0003_auto_20180302_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='possibly_sensitive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
