# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_scraper', '0004_auto_20180302_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='quoted_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
