# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_scraper', '0005_auto_20180302_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
