# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180609_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
